### GET BALANCE
GET http://localhost:8080/api/v1/account/123456789/balance

### WITHDRAWL FROM ACCOUNT
POST http://localhost:8080/api/v1/account/123456789/withdrawal
Content-Type: application/json

{
  "amount": 90
}