### GET BALANCE
GET http://localhost:8080/api/v1/account/123456789/balance
Authorization: 1234

### WITHDRAWL FROM ACCOUNT
POST http://localhost:8080/api/v1/account/123456789/withdrawal
Authorization: 12345
Content-Type: application/json

{
  "amount": 85
}

###
GET http://localhost:8080/api/v1/pin
Authorization: 4321